services:
  - type: web
    name: myfreehouseplans
    env: python
    plan: starter
    region: frankfurt
    autoDeploy: true
    buildCommand: |
      pip install -r requirements.txt
      cd plan2d_site
      python manage.py collectstatic --noinput --settings=config.settings.prod
      python manage.py migrate --noinput --settings=config.settings.prod
    startCommand: |
      cd plan2d_site
      gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings.prod
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: glehwvuv)tb%7gmgg-zlafxq)s&!o&uss6)h=2r#(593=y$f&p
      - key: ALLOWED_HOSTS
        value: "www.myfreehouseplans.com,.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: myfreehouseplans-db
          property: connectionString
      # Optional (only if you use Gumroad API calls server-side)
      - key: GUMROAD_API_KEY
        sync: false

databases:
  - name: myfreehouseplans-db
    plan: starter