services:
  - type: web
    name: myfreehouseplans
    env: python
    plan: starter
    region: frankfurt
    autoDeploy: true
    buildCommand: pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py collectstatic --noinput
    startCommand: gunicorn plan2d_site.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: plan2d_site.settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "www.myfreehouseplans.com,.onrender.com"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DATABASE_URL
        fromDatabase:
          name: myfreehouseplans-db
          property: connectionString
      # Optional (only if you use Gumroad API calls server-side)
      - key: GUMROAD_API_KEY
        sync: false

databases:
  - name: myfreehouseplans-db
    plan: starter